### PR TITLE
Port conformer_energies example from toolkit

### LINKED ISSUE #7: Port conformer energies example as a CLI function
The [`conformer_energies`](https://github.com/openforcefield/openforcefield/tree/0b026fb4072dd56a13e23e6aa2afd8734602da00/examples/conformer_energies) example in the toolkit is already most of the way to being a more general CLI tool that can live here. Some of the internal logic can also be slightly refactored to use modular functions that can be re-used by other functionality (or may already exist in #4)

### PR DESCRIPTION
**Pull request by mattwthompson**
## Description
This PR ports the `conformer_energy` example from the OpenFF toolkit.

Resolves #7 

  - [x] Move common functions into a common module
  - [x] Manually ensure results are similar to existing toolkit example
  - [x] Add RMSD comparison
  - [ ] Look into storing and reporting data in a dataframe

### CODE REVIEW

**Comment by mattwthompson** [comment]
Needs some cleanup but it does ultimately appear to be running the same results as the toolkit code:


```
(openff-dev) [openff-cli] python ../openforcefield/examples/conformer_energies/conformer_energies.py --filename ../openforcefield/openforcefield/data/molecules/ruxolitinib_conformers.sdf
1 unique molecule(s) loaded, with 10 total conformers
Parametrizing ruxolitinib (may take a moment to calculate charges)
Conformer         Initial PE         Minimized PE       RMS between initial and minimized conformer
    1 /    10 :   29.796 kcal/mol   -0.661 kcal/mol     0.800 Angstroms
    2 /    10 :   38.940 kcal/mol    0.679 kcal/mol     0.554 Angstroms
    3 /    10 :   74.890 kcal/mol    0.527 kcal/mol     0.952 Angstroms
    4 /    10 :   36.028 kcal/mol    1.163 kcal/mol     0.764 Angstroms
    5 /    10 :   36.969 kcal/mol    1.768 kcal/mol     1.011 Angstroms
    6 /    10 :   38.434 kcal/mol   -0.980 kcal/mol     0.639 Angstroms
    7 /    10 :   37.656 kcal/mol    0.983 kcal/mol     1.127 Angstroms
    8 /    10 :   27.831 kcal/mol   -0.212 kcal/mol     0.988 Angstroms
    9 /    10 :   33.442 kcal/mol   -0.627 kcal/mol     1.101 Angstroms
   10 /    10 :   35.742 kcal/mol   -1.599 kcal/mol     0.642 Angstroms
(openff-dev) [openff-cli] python openff/cli/get_conformer_energies.py --toolkit rdkit --forcefield openff-1.1.0 --molecule ../openforcefield/openforcefield/data/molecules/ruxolitinib_conformers.sdf --constrained True
1 unique molecule(s) loaded, with 10 total conformers
printing mol 0, minimized against openff-1.1.0
    1 /    10 :   29.796 kcal/mol   -0.661 kcal/mol     0.000 Angstroms
    2 /    10 :   38.940 kcal/mol    0.679 kcal/mol     0.000 Angstroms
    3 /    10 :   74.890 kcal/mol    0.527 kcal/mol     0.000 Angstroms
    4 /    10 :   36.028 kcal/mol    1.163 kcal/mol     0.000 Angstroms
    5 /    10 :   36.969 kcal/mol    1.768 kcal/mol     0.000 Angstroms
    6 /    10 :   38.434 kcal/mol   -0.980 kcal/mol     0.000 Angstroms
    7 /    10 :   37.656 kcal/mol    0.983 kcal/mol     0.000 Angstroms
    8 /    10 :   27.831 kcal/mol   -0.212 kcal/mol     0.000 Angstroms
    9 /    10 :   33.442 kcal/mol   -0.627 kcal/mol     0.000 Angstroms
   10 /    10 :   35.742 kcal/mol   -1.599 kcal/mol     0.000 Angstroms

**Comment by mattwthompson** [comment]
Looking better now: 

```shell
(openff-dev) [openff-cli] python openff/cli/get_conformer_energies.py --toolkit rdkit --forcefield openff-1.1.0 --molecule ../openforcefield/openforcefield/data/molecules/ruxolitinib_conformers.sdf --constrained True
1 unique molecule(s) loaded, with 10 total conformers
printing mol 0, minimized against openff-1.1.0
    1 /    10 :   29.796 kcal/mol   -0.661 kcal/mol     0.800 Angstroms
    2 /    10 :   38.940 kcal/mol    0.679 kcal/mol     0.554 Angstroms
    3 /    10 :   74.890 kcal/mol    0.527 kcal/mol     0.952 Angstroms
    4 /    10 :   36.028 kcal/mol    1.163 kcal/mol     0.764 Angstroms
    5 /    10 :   36.969 kcal/mol    1.768 kcal/mol     1.011 Angstroms
    6 /    10 :   38.434 kcal/mol   -0.980 kcal/mol     0.639 Angstroms
    7 /    10 :   37.656 kcal/mol    0.983 kcal/mol     1.127 Angstroms
    8 /    10 :   27.831 kcal/mol   -0.212 kcal/mol     0.988 Angstroms
    9 /    10 :   33.442 kcal/mol   -0.627 kcal/mol     1.101 Angstroms
   10 /    10 :   35.742 kcal/mol   -1.599 kcal/mol     0.642 Angstroms
(openff-dev) [openff-cli] python ../openforcefield/examples/conformer_energies/conformer_energies.py --filename ../openforcefield/openforcefield/data/molecules/ruxolitinib_conformers.sdf
1 unique molecule(s) loaded, with 10 total conformers
Parametrizing ruxolitinib (may take a moment to calculate charges)
Conformer         Initial PE         Minimized PE       RMS between initial and minimized conformer
    1 /    10 :   29.796 kcal/mol   -0.661 kcal/mol     0.800 Angstroms
    2 /    10 :   38.940 kcal/mol    0.679 kcal/mol     0.554 Angstroms
    3 /    10 :   74.890 kcal/mol    0.527 kcal/mol     0.952 Angstroms
    4 /    10 :   36.028 kcal/mol    1.163 kcal/mol     0.764 Angstroms
    5 /    10 :   36.969 kcal/mol    1.768 kcal/mol     1.011 Angstroms
    6 /    10 :   38.434 kcal/mol   -0.980 kcal/mol     0.639 Angstroms
    7 /    10 :   37.656 kcal/mol    0.983 kcal/mol     1.127 Angstroms
    8 /    10 :   27.831 kcal/mol   -0.212 kcal/mol     0.988 Angstroms
    9 /    10 :   33.442 kcal/mol   -0.627 kcal/mol     1.101 Angstroms
   10 /    10 :   35.742 kcal/mol   -1.599 kcal/mol     0.642 Angstroms

**Review by j-wags — APPROVED** [review]
This looks great, and I'm especially happy with the refactoring to add type hints. We'll want to think of how to communicate the deprecation of the OpenFF Toolkit's version of this script, but that isn't blocking a merge here!

**Comment by mattwthompson** [comment]
Thanks!

**Pull request merged**
